version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - friendoye
  ignore:
  - dependency-name: com.diffplug.spotless
    versions:
    - 5.10.2
    - 5.11.0
    - 5.11.1
    - 5.12.0
    - 5.12.1
  - dependency-name: com.airbnb.android:epoxy-processor
    versions:
    - 4.3.1
    - 4.4.0
    - 4.4.1
    - 4.4.2
    - 4.4.3
    - 4.4.4
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 7.0.0-alpha04
    - 7.0.0-alpha05
    - 7.0.0-alpha06
    - 7.0.0-alpha07
    - 7.0.0-alpha08
    - 7.0.0-alpha09
    - 7.0.0-alpha10
    - 7.0.0-alpha12
  - dependency-name: com.airbnb.android:epoxy
    versions:
    - 4.3.1
    - 4.4.0
    - 4.4.1
    - 4.4.2
    - 4.4.4
  - dependency-name: com.karumi:shot
    versions:
    - 5.10.0
    - 5.10.3
    - 5.5.1
    - 5.7.0
    - 5.8.0
  - dependency-name: io.mockk:mockk
    versions:
    - 1.10.6
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21-2
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.31
  - dependency-name: org.robolectric:robolectric
    versions:
    - "4.5"
